Section "Device"
    Identifier "Intel Graphics"
    Driver "modesetting"
    Option "AccelMethod" "glamor"
    Option "DRI" "3"
EndSection

Section "Device"
    Identifier "modesetting"
    Driver "modesetting"
    Option "AccelMethod" "SNA"
    Option "TearFree" "true"
EndSection
