# produce a unified kernel image and enable efi runtime functions
uefi="yes"
efi="runtime"

kernel_cmdline="cryptdevice=PARTUUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:root \
                rd.luks.uuid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx \
                rd.luks.key=/swap.key.gpg:PARTUUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                rd.luks.options=discard \
                zswap.enabled=1 zswap.compressor=lz4 zswap.max_pool_percent=20 zswap.accept_threshold_percent=80 zswap.shrinker_enabled=1 \
                quiet splash"

# restoring generic generation
hostonly="yes"

# adding modules to be included in the final initramfs
add_dracutmodules+=" crypt crypt-gpg dm fips integrity lvmthinpool-monitor \
                     masterkey modsign rescue rootfs-block securityfs \
                     systemd usrmount "

# using dracut to upgrade the metadata (xfs)
install_items+=" /usr/sbin/xfs_admin /usr/bin/expr "

# new method without initram-fs/disk (efistub compatible), see /etc/portage/make.conf
# explicit microcode loading enablement
# early_microcode="yes"

# omit the nvidia driver from the ramdisk, to avoid needing to regenerate the ramdisk on updates
omit_drivers+=" nvidia nvidia-drm nvidia-modeset nvidia-uvm "

# register backlight control on nvidia laptops
acpi_backlight="nvidia_wmi_ec"
