uefi="yes"
kernel_cmdline="cryptdevice=PARTUUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:root                                                            \
                rd.luks.uuid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx                                                                         \
                rd.luks.options=discard                                                                                                   \
                zswap.enabled=1 zswap.compressor=lz4 zswap.max_pool_percent=20 zswap.accept_threshold_percent=80 zswap.shrinker_enabled=1 \
                quiet splash"
compress="lz4"
hostonly="yes"

add_dracutmodules+=" crypt dm kernel-modules lvm            \
                     modsign rescue rootfs-block securityfs \
                     systemd udev-rules "
install_items+=" /usr/sbin/xfs_admin /usr/bin/expr "
omit_drivers+=" nvidia nvidia-drm nvidia-modeset nvidia-uvm "

# new method without initram-fs/disk (efistub compatible), see /etc/portage/make.conf
# explicit microcode loading enablement
# early_microcode="yes"