timeout: 5
remember_last_entry: yes

# custom limine theme
term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: ffffffff
term_foreground: cdd6f4
term_background_bright: ffffffff
term_foreground_bright: cdd6f4
#interface_branding:
wallpaper: boot():/gnu-linux-splash.png

#comment: machine-id=
/Linux
//gentoo
  protocol: efi
  #comment: Kernel version: <version>-gentoo
  #comment: kernel-id=gentoo
  path: boot():/EFI/Linux/<uki>.efi
