[Settings]
gtk-theme-name=Windows XP Metallic
#gtk-icon-theme-name=Chicago95-tux
gtk-font-name=Noto Sans Regular 10
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
